name: release

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit and Doc Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Unit tests
        run: cargo test

  lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Linting
        run: cargo clippy -- -Dwarnings

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check Formatting
        run: cargo fmt --check
